### ISSUE TITLE
Collate these into an ESLint Ruleset

### ISSUE THREAD

**Issue by Eishpirate** [thedaviddias/Front-End-Checklist#118]
Hey all,

Not sure if this is the right forum for this, but wouldn't it be great if we could just run an ESLint Ruleset for all these rules, rather than having to manually check them everytime you do a Production release?

Else maybe a Webpack addon?

Or am I being silly?

**Comment by thedaviddias** [comment]
Hey @Eishpirate, no I'm sure you are absolutely not silly 😅

ESLint is only for JavaScript rules and doesn't apply to a lot of elements you can find in the checklist. The closest tool is Lighthouse who test some elements we have here, but not all.

As soon as the checklist will be stabilized, maybe some elements will be integrated into Lighthouse or a specific tool will be made.

**Comment by thedaviddias** [comment]
Oh and a new type of link will maybe show some existing package that can help to automate some tests (gulp, webpack and npm packages)

**Comment by Leakermeli** [comment]
ohhh that is so interesting
