### ISSUE TITLE
role attributes on <nav> and <main> are superfluous

### ISSUE THREAD

**Issue by Daniel-Hug** [thedaviddias/Front-End-Checklist#134]
This is the **Landmarks** section under **Accessibility** > **Best Practices**:

#### Landmarks

- [ ] **Role banner:** High `<header>` has `role="banner"`.
- [ ] **Role navigation:** High `<nav>` has `role="navigation"`.
- [ ] **Role main:** High `<main>` has `role="main"`.

> * 📖 [Using ARIA landmarks to identify regions of a page](https://www.w3.org/WAI/GL/wiki/Using_ARIA_landmarks_to_identify_regions_of_a_page)
> * 📖 [ARIA roles categorization](https://www.w3.org/TR/wai-aria/roles#roles_categorization)

---

Comments:
- The second link is a 404.
- The HTML5 elements mentioned here already come with an implied role. In 2012 the Web Content Accessibility Guidlines [recommended](https://www.w3.org/WAI/GL/wiki/index.php?title=Using_HTML5_nav_element&oldid=1635#Example:The_.3Cnav.3E_element) you still use a `role` attribute until support for these elements came to screen readers: 

  > When support for HTML5 improves there may be no need to continue to add the ARIA role="navigation".

  - Because of the wide support for these elements today (at least in browsers — I don't use a screen reader), I think it's unnecessary to specify the same role in an attribute as well.
  - [Bootstrap puts this better than me](https://getbootstrap.com/docs/4.0/components/navbar/#how-it-works): Ensure accessibility by using a `<nav>` element or, if using a more generic element such as a `<div>`, add a `role="navigation"` to every navbar to explicitly identify it as a landmark region for users of assistive technologies.

**Comment by elliottregan** [comment]
These roles are still needed. Even recent versions of VoiceOver fails to show these regions in the rotor.

The second link works for me.

**Comment by Daniel-Hug** [comment]
Thanks Elliot.

**Comment by wingatekr** [comment]
I was going to open this one too, but voiceover is a very popular reader, and if it doesn't support, particularly on mobile, than we should include the manual roles still.
