### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by alifouad991** [thedaviddias/Front-End-Checklist#138]
Hello thanks for your support can you tell me how to use it do i need to upload it to my server and run some file or how please do let me know

**Comment by lucalves** [comment]
Hello, @alifouad991. From what I understand, it's just an informative repository of best practices within front-end web programming.

**Comment by thedaviddias** [comment]
Hi @alifouad991 and @lucalves, in the next days I'll launch a dynamic tool to facilitate the use of the checklist in your workflow.

But for now, I don't have a tool that can test your page... for now.

**Comment by thedaviddias** [comment]
@alifouad991 @lucalves Now you can check the 🔥 NEW Front-End Checklist Application 🔥, it's dynamic and can manually generate reports! Enjoy 🎉! ➜ http://bit.ly/frontendchecklist
