### ISSUE TITLE
Viewport for iPhone X

### ISSUE THREAD

**Issue by GYTO** [thedaviddias/Front-End-Checklist#160]
For the 'HEAD' section I would consider to update the viewport meta tag.
According to this article -> [https://webkit.org/blog/7929/designing-websites-for-iphone-x/](WebKit iPhone X)
`<meta name='viewport' content='initial-scale=1, viewport-fit=cover’>`
It's better to change to 
`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">`
that will support iPhone X viewport save zone

**Comment by thedaviddias** [comment]
Yes you are right, can you do a PR?
