### ISSUE TITLE
Translation to Ukrainian

### ISSUE THREAD

**Issue by GYTO** [thedaviddias/Front-End-Checklist#164]
I was checking other translation of this repo and I think it will good fit if we translate it Ukrainian. Repo already has Russian translation, but I think is a good idea to add some flavor to it.

Would you accept another translation?

**Comment by thedaviddias** [comment]
Yes sure! More translation we have better that can help people around 👍

**Comment by GYTO** [comment]
btw, David did you think about adding a button on the checklist website to change languages?

**Comment by thedaviddias** [comment]
Yes, I'm actually working on that. You'll need to translate all JSON files existing. Subscribe to the newsletter on the website, you'll be informed about all new evolutions.

**Comment by thedaviddias** [comment]
@GYTO Any update? Can you close the issue?

**Comment by thedaviddias** [comment]
@GYTO Any update? Can you close the issue?
