### ISSUE TITLE
Sometimes, checklist gets double checked, resulting in unknown status

### ISSUE THREAD

**Issue by kesuskim** [thedaviddias/Front-End-Checklist#165]
Hello, you have updated your checklist site, https://frontendchecklist.io/ . Glad to see it :+1: 

I have tested something, then I realize, sometimes checkbox got double-checked. This is example image of the result.

![image](https://user-images.githubusercontent.com/7637982/33056738-ae9cbeb4-ceca-11e7-8b0a-a26eee97d931.png)

I just clicked 'check all' button and went down, but I accidently click some item which is already checked (by check all), then 100% goes up to 105% and changes more dark-green, and right panel gets lost its color. :(

I tested some times more, but I saw that it happens without 'check all' button. I don't know when that happens, but it does happen sometimes.

Also, this situation happens not only in CSS section, so maybe there is some logic problem of checking item, I think.

**Comment by thedaviddias** [comment]
Thanks to flag that @kesuskim, it's a bug indeed. I'll work on that.
