### ISSUE TITLE
Trust and Scoping Web Content to Domains

### ISSUE THREAD

**Issue by normanbrobinson** [thedaviddias/Front-End-Checklist#17]
Needs to address having SSL certificates for authenticating the site and trusting content is from originating site. Seems like any front end development will be dependent upon a secure environment such that whatever is created is not hijacked with DNS poisoning of advert, man-in-the-middle attacks, trust, and generally keeping your wire-frames and transfer to partner sites planned properly.

- https://en.wikipedia.org/wiki/Same-origin_policy
- https://developers.google.com/web/fundamentals/security/csp/
- https://letsencrypt.org/getting-started/

**Comment by thedaviddias** [comment]
Indeed @normanbrobinson, all the security part needs to be added. Let me update you in the next days with new content about it.

**Comment by thedaviddias** [comment]
@normanbrobinson I added a security section, what do you think?

**Comment by thedaviddias** [comment]
Without any response, closing the ticket.
