### ISSUE TITLE
Translation to German

### ISSUE THREAD

**Issue by kaisershad** [thedaviddias/Front-End-Checklist#175]
Translate Front-End-Checklist to german, to make it available for germany, austria and switzerland.

@thedaviddias: Thanks for responding so quick in twitter 👍 . Should i fork your project and offer the german version under my github account? This is how i'm seeing it for the other translations. 
Thx
Kaiser

**Comment by thedaviddias** [comment]
Yes, indeed, you need to fork and translate the README which is on your fork.

**Comment by kaisershad** [comment]
Thanks. I will start with the translation and paste the link here when it's done 💯

**Comment by xFuture603** [comment]
@kaisershad. Bist du daran interessiert gemeinsam zu arbeiten? Würde mich bei der Übersetzung ENG -> DE, gern beteiligen! 

VG

**Comment by thedaviddias** [comment]
@kaisershad Have you been in contact with @xFuture603?

**Comment by xFuture603** [comment]
@thedaviddias I started the translation now on my own. Gonna hit you up with some updates.

**Comment by xFuture603** [comment]
@thedaviddias I finished my work with this translation right now. Translated everything in german now! :) Anything else I need to do now?

**Comment by kaisershad** [comment]
@xFuture603 Can you please share the repo, where the translation is? I also started it and if you like we can compare it.

**Comment by xFuture603** [comment]
@kaisershad I am sorry. I am already done with the entire translation!

**Comment by kaisershad** [comment]
@thedaviddias Hi, we can close this issue (my [german version](https://github.com/kaisershad/Front-End-Checklist/tree/1-german-translation)). I have 2 ideas:
1. Integrate the german translation direct to: https://frontendchecklist.io/
2. Searching the mentioned recourses in german language
Please let me know, if you think that there are useful.

**Comment by thedaviddias** [comment]
@kaisershad You can easily integrate the german translation on frontenchecklist.io, you can find an example with the JP language.
