### ISSUE TITLE
Add recommendation for humans.txt

### ISSUE THREAD

**Issue by Un3x** [thedaviddias/Front-End-Checklist#176]
I was checking the checklist and i couldn't find any recommandation about the humans.txt file.

What's your opinion about it ? Should it be added to the checklist ?

**Comment by thedaviddias** [comment]
It's indeed interesting you point that out. I used a humans.txt for the Front-End Checklist App but completely forgot to add it to the README.

On my POV, that could be mentioned as a LOW priority, but I think it can absolutely be in the FEC. Would like to have other POV.

**Comment by Un3x** [comment]
I totally agree with low priority. It's also very easy and fast to setup. Any one having POV about this ?

**Comment by thedaviddias** [comment]
@MrSunshyne any POV?
