### ISSUE TITLE
Slow scroll on chrome on links

### ISSUE THREAD

**Issue by Barterr** [thedaviddias/Front-End-Checklist#177]
When clicking the section links at the top of the page to scroll to the section, the scrolling is painfully slow on chrome. It works fine in firefox, it looks like it's a fixed 4 seconds to scroll to position, however on chrome it's janky and slow, and doesn't stop scrolling down until it gets there.

**Comment by reifnotreef** [comment]
I have this same issue on Chrome on Android. 
Tapped the HTML to jump to that section and it started scrolling about 0.5 lines a second.

**Comment by thedaviddias** [comment]
Thanks guys, indeed, I'll correct that asap. I'll keep you posted.

**Comment by Barterr** [comment]
Looks like it was fixed, closing this
