### ISSUE TITLE
Duplicate licenses?

### ISSUE THREAD

**Issue by tdmalone** [thedaviddias/Front-End-Checklist#18]
[LICENSE](https://github.com/thedaviddias/Front-End-Checklist/blob/master/LICENSE) says MIT, but [README.md](https://github.com/thedaviddias/Front-End-Checklist/blob/master/README.md) says CC0.

I'm assuming you intended CC0 but just wanted to clarify.

Thanks for the excellent work!

**Comment by thedaviddias** [comment]
Thanks @tdmalone, I think I did a mistake when I first created the repo. I'll update for CC0 not MIT. 😉
