### ISSUE TITLE
Code sponsor should be removed

### ISSUE THREAD

**Issue by OmgImAlexis** [thedaviddias/Front-End-Checklist#183]
[They're shutting down on december 8th](https://twitter.com/codesponsor/status/935139167075553281).

Commit: https://github.com/thedaviddias/Front-End-Checklist/commit/994ee12078a120b96644a1a23412578ae7d1e804

**Comment by Jayntlatleng** [comment]
Hey there can you please bring me to my comprehending on how is Github works in a easy way while am associating myself with you coz it seems so interesting please please pleeeeeeeeeease :open_mouth:

**Comment by Jayntlatleng** [comment]
It seems like you know this like you know yourself

**Comment by Jayntlatleng** [comment]
Coz what I can comprehend about Github is that is an app that you can create or build yourself an app inside of it

**Comment by Jayntlatleng** [comment]
....am I right or am l right?

**Comment by Jayntlatleng** [comment]
Please respond when when you got these messages

**Comment by thedaviddias** [comment]
Thanks @OmgImAlexis, I was aware of the shutdown. I removed the code.
