### ISSUE TITLE
Selecting each item individually on checklist giving only a B grade

### ISSUE THREAD

**Issue by emaadali** [thedaviddias/Front-End-Checklist#184]
When every item is manually marked as complete one by one, the grade is only a B.

<img width="350" alt="screen shot 2017-12-03 at 10 33 32 pm" src="https://user-images.githubusercontent.com/3521616/33535205-28b74aa8-d87a-11e7-9823-c30fa34c0eac.png">

This does not happen when you use `.js-check-all` to check all items in all sections.

Issue found in **Chrome 62.0.3202.94** [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36] and issue replicated in **Safari Version 10.1 (12603.1.30.0.34)**
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30]

**Comment by huyingjie** [comment]
I reproduced the issue reported by @emaadali . 
I did one additional step: refresh the webpage after manually marking all items as complete one by one, the grade will change to "A".

**Comment by thedaviddias** [comment]
Thanks guys, I'll correct that this week, don't hesitate if you find something else.

**Comment by RobertCordes** [comment]
This is still an issue
