### ISSUE TITLE
Doctype should be first line of the file

### ISSUE THREAD

**Issue by kjb** [thedaviddias/Front-End-Checklist#188]
Comment should not precede DOCTYPE.

The purpose of <!doctype html> is to ensure standards compliant rendering, avoiding quirks mode, even in older browsers.  To fulfill this purpose, it must be the first item in the file. See https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

"Make sure you put the DOCTYPE right at the beginning of your HTML document. Anything before the DOCTYPE, like a comment or an XML declaration will trigger quirks mode in Internet Explorer 9 and older."

**Comment by thedaviddias** [comment]
Thanks for the correction, indeed nothing should be before the Doctype.

**Comment by thedaviddias** [comment]
@kjb, if it's good for you can you close the issue?

**Comment by kjb** [comment]
Thanks!
