### ISSUE TITLE
Accessibility "role" suggestions seem outdated

### ISSUE THREAD

**Issue by JeffreyATW** [thedaviddias/Front-End-Checklist#194]
In HTML5, there shouldn't be a need to add `role` attributes to semantic elements, such as `header`, `nav`, and `main`. One piece of documentation points to [this article](https://www.w3.org/WAI/GL/wiki/Using_ARIA_landmarks_to_identify_regions_of_a_page?ref=frontendchecklist), which seems to be specific to HTML4 (it does not mention semantic elements).

The [other document](https://www.w3.org/TR/wai-aria/roles#roles_categorization?ref=frontendchecklist) lists out `banner`, `navigation`, and `main`, but none of them seem to mention the related semantic elements (although the `nav` element is specified as a "related concept").

Are there any other sources that explicitly specify that these roles must exist on these elements?

**Comment by JeffreyATW** [comment]
BTW, the [Nu Html Checker](https://validator.w3.org/nu/) suggests that these `role` attributes are unnecessary.

**Comment by thedaviddias** [comment]
Hey @JeffreyATW, indeed you are right, few people point that out. Do you want to do a PR for that and remove what is not necessary?
