### ISSUE TITLE
Introduce persistance beyond browser localstorage etc.

### ISSUE THREAD

**Issue by mmodrow** [thedaviddias/Front-End-Checklist#202]
I whipped up a little something for Tampermonkey to add load & save on the dev tool command line with JSON as transfer format.

[https://gist.github.com/MarcAMo/93dbaae65fc5621eb9619d14e6d760c0](https://gist.github.com/MarcAMo/93dbaae65fc5621eb9619d14e6d760c0)

This way you can hand over form state to other people or browsers or even put it in a repo together with the checked code.

Maybe something like this should be in the GUI?

**Comment by thedaviddias** [comment]
Nice @MarcAMo! I wasn't aware about Tampermonkey (don't know how I missed that).

I need to check if that can be added on the app or not.

**Comment by MarcAMo** [comment]
I haven't yet had a look at your codebase, but if you'd like I could see if I could come up with something and then commit a PR.

**Comment by thedaviddias** [comment]
Feel free to make any change you want ☺️ I still need to write a real README_APP but you can add some code and I can review it after.

**Comment by MarcAMo** [comment]
I opened a PR last weekend.
When you've got time, I think we should move the conversation there. (It still git codeclimate issues, because I don't know how to better give the user feedback in your app other than alerts. Other than that we're green analytics-wise.)

**Comment by thedaviddias** [comment]
Hi @MarcAMo, I'm sorry for the delay, I'm actually not able to work on that. Let me see what is wrong in the next days. Thanks for your patience and understanding.

**Comment by MarcAMo** [comment]
No problem. Happy holidays and a happy new year!

**Comment by danieledler** [comment]
Just checking if the pull request for this issue is still something to consider it seems to have been forgotten?

**Comment by mmodrow** [comment]
I can happily use my fork, if need be. But as I moved on from web to app development even that appears not likely. Take it if you wish or abandon it, if you don’t. I am happy both ways.
