### ISSUE TITLE
Check all button not reflected in print preview

### ISSUE THREAD

**Issue by HZooly** [thedaviddias/Front-End-Checklist#206]
## How to reproduce?

Check some checkboxes in the list (not 100% of a category). In a category, click on *Check all items* button.

Generate a report: it should open a print preview (Chrome Browser). 

Generated report shows that there's 100% items checked in the category, but checkboxes that have been checked by *Check all items* button are not checked.

Sorry for the abusive **check** words 😈

**UI list**

<img width="625" alt="capture d ecran 2017-12-28 a 00 34 18" src="https://user-images.githubusercontent.com/7328625/34396117-4c0a336c-eb67-11e7-8be7-f95a209f0a7a.png">

**Generated report**

<img width="392" alt="capture d ecran 2017-12-28 a 00 34 09" src="https://user-images.githubusercontent.com/7328625/34396116-4bed17d2-eb67-11e7-8982-8c84e36321e4.png">

## Seen on

- macOS High Sierra (10.13.1)
- Chrome (63.0.3239.84)

**Comment by thedaviddias** [comment]
Interesting bug indeed. I'll take a look on that. Thanks for the flag @TorzuoliH!

**Comment by TorzuoliH** [comment]
Thanks to you! I've added additional informations.

**Comment by HZooly** [comment]
@thedaviddias any news on it? I don't know if it stills happen.

**Comment by thedaviddias** [comment]
Hi @HZooly, sorry for the late response, I'll be working on correcting all the bugs in the next days. I'll keep you posted.

**Comment by HZooly** [comment]
I've tested this one again, it stills happen 😄 
Maybe this weekend I'll find some time to work on this issue @thedaviddias
