### ISSUE TITLE
Clicking "Expand all items" more than once duplicates all code snippets in that section

### ISSUE THREAD

**Issue by seanbrousseau** [thedaviddias/Front-End-Checklist#207]

**Comment by Gregjarvez** [comment]
@seanbrousseau Hello I would Like to work on this problem, however, I am having a hard time finding which part of the triggers this action. A little assistance will be appreciated

**Comment by shmulim** [comment]
Fixed.

https://github.com/thedaviddias/Front-End-Checklist/pull/224

**Comment by shmulim** [comment]
Fixed. #224

**Comment by thedaviddias** [comment]
The pull request was accepted, thanks for the work. Please close the ticket if it's good for you.
