### ISSUE TITLE
Accessibility: Do not remove outline style

### ISSUE THREAD

**Issue by vcastrejont** [thedaviddias/Front-End-Checklist#216]
All browsers have a default value they apply to the currently focused item. This is especially useful for folks who can't use a mouse or have a visual impairment. If you remove the outline you are making your site inaccessible for these people.

Avoid using:
`:focus {
outline: 0;
}`

Keyboard users depend on this outline to determine where they are on the page.

**Comment by thedaviddias** [comment]
Hi @vcastrejont, indeed but it's possible to remove the focus IF a creative feedback is provided on some elements.

**Comment by Malvoz** [comment]
Yes, the outline is important for keyboard-only users. You can remove the `outline` for `:focus` and add back `outline`s for keyboard-only users with [`:focus-visible`](https://caniuse.com/#search=focus-ring).
