### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [thedaviddias/Front-End-Checklist#226]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by thedaviddias** [comment]
Hi @dbucci24, no it is not! Feel free to fork the project and do the translation in Spanish 👍

**Comment by gabrielizalo** [comment]
Yesss.. It is here: [https://github.com/eoasakura/Front-End-Checklist-ES](https://github.com/eoasakura/Front-End-Checklist-ES)

**Comment by thedaviddias** [comment]
Hic... Sorry @gabrielizalo, I completely forgot that the README was translated in Spanish but nonetheless, the app is not :) So feel free @dbucci24 to work on the JSON files to create the frontendchecklist.io in Spanish!

**Comment by gabrielizalo** [comment]
Sorry... I forgot about.. It was translated or not? @thedaviddias how translate the app with json files?

**Comment by thedaviddias** [comment]
Hi @gabrielizalo, nope, but I'm going to launch a better and more complete version of the FEC, maybe it's better to way for the version 2 :)

**Comment by gabrielizalo** [comment]
Ok.. Thanks...
