### ISSUE TITLE
`<code>lang</code>` is escaped

### ISSUE THREAD

**Issue by GrosSacASac** [thedaviddias/Front-End-Checklist#233]
> The <code>lang</code> attribute of your website is specified and related to the language of the current page.

`<code>lang</code>` is escaped

https://frontendchecklist.io/

**Comment by thedaviddias** [comment]
Hi @GrosSacASac, thanks to reach the issue, do you want to open a PR?

**Comment by robinmetral** [comment]
Also this specific item doesn't expand on [https://frontendchecklist.io](https://frontendchecklist.io) I see in README.md that it should be expanding into `<html lang="en">`.
Same issue for other items such as Direction attribute, RSS feed, etc.
