### ISSUE TITLE
Urgency indicator colors on the website aren't colourblind friendly

### ISSUE THREAD

**Issue by Tobsta** [thedaviddias/Front-End-Checklist#237]
The task urgency indicators (little coloured dots left of the checkboxes) are impossible for me to discern as a colourblind person. It would be great if you reused the coloured boxes from the README file like this: ![image](https://user-images.githubusercontent.com/11626018/37125381-6fd5b1aa-22c0-11e8-929c-25aa34507b2b.png)

I would do it myself but I'm unsure of whether you're using a build system to generate the monolithic HTML file or not.

**Comment by thedaviddias** [comment]
Hi @Tobsta, thanks to flag that out. I'm sorry for that mistake, it's on me. Feel free to correct it in the SCSS file, if you don't know how to do, I'll correct it in the next days. Do you have a suggestion for the alternative color?
