### ISSUE TITLE
Minification and HTP/2

### ISSUE THREAD

**Issue by Oblium** [thedaviddias/Front-End-Checklist#25]
In the optimization section you state:

Minification: High All CSS files are minified. (Not for HTTP2)

Actually you should minify the CSS even with http2 because this protocol will compress Headers, not the body of communications. 

Ref:
 * https://http2.github.io/http2-spec/compression.html

**Comment by thedaviddias** [comment]
Oops, yes @Oblium your are rignt. Only the concatenation part is different for HTTP/2. Thanks to point that.
