### ISSUE TITLE
Generating/printing report shows the footer URL

### ISSUE THREAD

**Issue by salamwaddah** [thedaviddias/Front-End-Checklist#254]
When I use the [demo website](https://frontendchecklist.io/) and try to generate a report then scroll down to the bottom on the report you will see the URL is visible when printing and not hidden behind the text (David Dias "The")

![screen shot 2018-05-06 at 5 05 03 pm](https://user-images.githubusercontent.com/26627088/39673592-61543b88-5150-11e8-9922-32574ea28e44.png)

I think adding the following to CSS will fix this:
```
a[href]:after {
   content: initial;
}
```
Now when generating a report the link will be hidden:
![screen shot 2018-05-06 at 5 09 30 pm](https://user-images.githubusercontent.com/26627088/39673589-582bdd7c-5150-11e8-8c77-0f8a597be909.png)

**Comment by thedaviddias** [comment]
That was done on purpose because on the print version you can't see the href of a link, but I don't mind to remove it, if you feel that's not appropriate. Do you want to do a PR @salamwaddah?

**Comment by LIYINGZHEN** [comment]
@thedaviddias I have created a PR #279. Let me took care of fixing it.

**Comment by thedaviddias** [comment]
Thanks @LIYINGZHEN! @salamwaddah, I think you can close the issue now.
