### ISSUE TITLE
Make website checkbox clickable 

### ISSUE THREAD

**Issue by MUCHZER** [thedaviddias/Front-End-Checklist#26]
Can we make website checkbox clickable and (why not) count them with a sticky counter on the bottom on the screen ?

Would be happy to work on this, I just dont know how to contribute if I'm doing javascript.

**Comment by thedaviddias** [comment]
@MUCHZER, unfortunately Github don't allow the checkbox to be clickable 😕. I'm already working on a simple webapp with all the elements in the checklist.

I'll tell you when the repo will be on Github, I hope we'll be able to work on that together 😉

**Comment by MUCHZER** [comment]
Great! Just @ me ;)
