### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by TheDutchCoder** [thedaviddias/Front-End-Checklist#261]
Inline CSS is marked as being a bad thing, but this is not the case for critical CSS, which actually improves (perceived) performance and there are a couple of tools available to help with this.

I would consider changing this checkpoint and/or add one for critical CSS.

**Comment by Kout** [comment]
You are right with critical CSS, anyway I would say this technique becomes obsolete with rise of HTTP/2 and splitting CSS/JS files in chunks. So in contrary maybe it is time to suppress it completely in the list.
