### ISSUE TITLE
Add an animation section?

### ISSUE THREAD

**Issue by MaskyS** [thedaviddias/Front-End-Checklist#28]
Hey David, nice checklist! Here's a suggestion: I'm no professional, but from a user point of view, using animation can absolutely change the way users interact with websites if done right. Maybe add some stuff about this? Thanks again!

-Masky

**Comment by thedaviddias** [comment]
Hey @MaskyS! I hesited to add that kind of section... But I don't know if it's something to put on that checklist... The Front-End, in general, integrate animations with CSS / JavaScript that are suggested by the creative team. Maybe at least a *check* can be added for the FE to ensure these animations are working properly on the website.

But I don't see this like a *requirement* that needs to be done by the Front-End developer... What do you think?

**Comment by dorian-delorme** [comment]
Hey,

I agree about the utility of an animation section, but maybe focus on performance ?
By the way, thanks @thedaviddias for this awesome checklist!

- Dorian

**Comment by thedaviddias** [comment]
@MaskyS, @dorian-delorme do you have any items to suggest?
