### ISSUE TITLE
Recommendation Link AMP

### ISSUE THREAD

**Issue by torresgol10** [thedaviddias/Front-End-Checklist#288]
I think it would be important to add this section to the checklist.

```<link rel="amphtml" rel="" />```

https://www.ampproject.org

**Comment by thedaviddias** [comment]
Good point, don't hesitate to do a PR, otherwise, I'll add a rule about. Thanks!

**Comment by torresgol10** [comment]
I need your help to do a gulp dev I get this problem as I can fix it "Requiring external module babel-register", I read it is solved by installing babel/core.

I will also try to take time to start translating the project into Spanish XD

**Comment by thedaviddias** [comment]
I need to update everything and check. I don't remember exactly what I did to make it work... Did you installed gulp-cli globally?

**Comment by torresgol10** [comment]
Sorry, it was a mistake of my gulp-cli, I already have it mounted I am preparing the PR
