### ISSUE TITLE
Add structured data (schema.org) to SEO list

### ISSUE THREAD

**Issue by ferdiemmen** [thedaviddias/Front-End-Checklist#29]
I am missing a checkbox for structured data like schema.org.

Addition to the README.md
* [ ] **Schema schema.org:** ![High](http://res.cloudinary.com/djnyaloac/image/upload/v1508238836/level-checklist-high.png) Structured data helps crawlers understand the content in the current page.

**Comment by thedaviddias** [comment]
Hi @ferdiemmen, I mentioned *structured data* in the HTML part.

>  Structured Data: High Pages using structured data are tested and are without errors.

Do you think, we need to duplicate the entry or remove from HTML and put on SEO?

**Comment by ferdiemmen** [comment]
I think we should indeed remove it from HTML and add it to SEO. Structured data could be added on DOM elements but the preferred way nowadays is using ld+json.

**Comment by thedaviddias** [comment]
Yes indeed, agree. Let's make the change.
