### ISSUE TITLE
Ensure there is an explanation with each point

### ISSUE THREAD

**Issue by BrianDGLS** [thedaviddias/Front-End-Checklist#3]
Firstly thank you for publishing this list it's very useful.

I've noticed that some of the points have no explanation as to why they are needed.

As an example:
`A meta description is provided, it is unique and doesn't possess more than 150 characters.`

Why does it need to be provided?
Why does it need to be unique?
Why should it not possess more than 150 characters?
What happens if I don't include it?

Some points do have links to other resources or documentation, however a short inline explanation would be very useful.

**Comment by thedaviddias** [comment]
Indeed BrianDGLS, thanks to point that out. I plan to add much more explanations and have at least 2 links for each point to help understand better.

I'll start to include your suggestions in the next days. If you have any suggestion, don't hesitate to do a PR.

**Comment by webdevan** [comment]
Its nice to use this as a checklist of things to check (short bullet points). Links to more info are great, but I think it's good to keep the checklist brief (and just link to other pages for the reasoning).

**Comment by thedaviddias** [comment]
@webdevan, good point too indeed and it was the first purpose of the checklist: having something short but with enough information.

**Comment by DarekRomanowski** [comment]
Google officially increases length of snippets (meta description) in search results 1 week ago: https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596
