### ISSUE TITLE
The website has diverged from the README

### ISSUE THREAD

**Issue by jtenclay** [thedaviddias/Front-End-Checklist#302]
It seems like the README has been continually updated and formatted, but the website items don't match up anymore. Is there something I can help with to bring the website back up to date? Could the build be changed in some way so that the data items and README are connected somehow?

**Comment by naeluh** [comment]
The website does not seem to work anymore? I keep getting an F for any site?

**Comment by thedaviddias** [comment]
@jtenclay I'm sorry for the delay of my response, if you want to update the content of the website, you just need to update the JSON files inside the data folder. I'm actually improving the content, so hopefully, we'll have soon a better version of the README / website.

@naeluh I just checked and the website seems to be working properly... what is exactly the issue you have?

**Comment by jtenclay** [comment]
@thedaviddias Not a problem, thanks for the response! If you're planning to be changing some of the content I'll give some space for now and check back later.

The deeper question was if it makes sense for the content to be stored in two places, since other contributors might update the README but forget to update the JSON (for example). But if you feel good with it, then I'm sure it's no problem 👍
