### ISSUE TITLE
Japanese page is not available

### ISSUE THREAD

**Issue by willowcheng** [thedaviddias/Front-End-Checklist#308]
![screen_shot_2019-01-23_at_3_42_03_pm](https://user-images.githubusercontent.com/6239076/51635738-852bc500-1f25-11e9-942e-52977c344e8a.png)
Inside https://frontendchecklist.io/, the Japanese path doesn't actually work, which shows following:
![screen shot 2019-01-23 at 3 40 13 pm](https://user-images.githubusercontent.com/6239076/51635770-95dc3b00-1f25-11e9-8be3-10bbd89d1503.png)

**Comment by thedaviddias** [comment]
Thanks @willowcheng, I'm gone take a look on that

**Comment by thedaviddias** [comment]
@willowcheng the Japanese version was removed at it requires some work and I'm currently working on another version.
