### ISSUE TITLE
Consider linking to an accessibility checklist

### ISSUE THREAD

**Issue by garcialo** [thedaviddias/Front-End-Checklist#312]
I would suggest this one: https://a11yproject.com/checklist.html

**Comment by thedaviddias** [comment]
Hi @garcialo, I'm actively working on the Front-End Accessibility Checklist... hopefully will be out in the next weeks! 😉

**Comment by garcialo** [comment]
Great. Let me know if you'd like some assistance. I've created a few over the years.

**Comment by kodeGenius** [comment]
Hi @thedaviddias, I can see that Front-End Accessibility Checklist is up. Except if you have additional update, I would suggest that this issue is close.
