### ISSUE TITLE
Arabic translation is ready.

### ISSUE THREAD

**Issue by iAbdullahWaleed** [thedaviddias/Front-End-Checklist#320]
I translated the checklist to arabic but on separate page, because github don't support rtl very well.
Url : https://iabdullahwaleed.github.io/FrontEnd-Checklist/

**Comment by thedaviddias** [comment]
@iAbdullahWaleed nice! Feel free to open a PR to add your link on that section https://github.com/thedaviddias/Front-End-Checklist#translations
