### ISSUE TITLE
Order of Meta Viewport Tag in Head

### ISSUE THREAD

**Issue by kylejrp** [thedaviddias/Front-End-Checklist#326]
The Head section says:
> The next 2 meta tags (Charset and Viewport) need to come first in the head.

I found a reference for Charset being early on in the head:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
> The `<meta>` element declaring the encoding must be inside the `<head>` element and within the first 1024 bytes of the HTML as some browsers only look at those bytes before choosing an encoding.

However, I can't find a reference for why `viewport` should be placed at the beginning of the `<head>` element. What's the motivation behind putting `viewport` in the first two elements of the `<head>` element?

**Comment by steegarden** [comment]
From my understanding, it’s not that it necessarily has to go first, it’s that it either has to be placed above a title tag or below other meta tags to work properly in the head element.

**Comment by elbrant** [comment]
Understandably, `<meta charset ...`  should immediately follow the opening `<head>` tag of your document. It declares the character encoding required for the page.  I add my `<meta viewport ...` tag immediately after that, along with any/all other `<meta... ` tags.  

I group all of the tags in my `<head>` together for readability, (all my `<meta ...` tags, then `<title>`, followed by any/all of my `<link ...` tags,, etc.).  If I have to go back to verify or change something, I don't have to hunt for it.

**Comment by Dikshit-Kapoor** [comment]
Understand, it is not necessary that meta tag should be written just after opening <head> tag of your document it can be written even after the <title> tag and then  you can add other links also, for example:
<head>
	<title></title>
		<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="">
</head>
