### ISSUE TITLE
Percentage completion may exceed 100%

### ISSUE THREAD

**Issue by jeshan** [thedaviddias/Front-End-Checklist#327]
Scenario:
- clear local storage
- refresh page
- tick all in a certain section (as indicated in screenshot); in my example, head section becomes 100%
- tick any of the items in this same section; head becomes 105%. (19/18*100 = 105)

![image](https://user-images.githubusercontent.com/1020565/62734153-598fa880-ba39-11e9-9c1e-2a37ffc49ef4.png)

**Comment by thedaviddias** [comment]
Thanks for the correction @jeshan
