### ISSUE TITLE
[Bug] Check/Uncheck all button bug

### ISSUE THREAD

**Issue by Jack89ita** [thedaviddias/Front-End-Checklist#331]
Hello!
When checking/unchecking all boxes within a section with the button, visually the result is correct, but when i try to print the report, all those checkboxes are not correct.

Step to reproduce:
1- Check all boxes of a section with the button "Check all item"
2- Click "Generate report"

Thank you!

**Comment by vishal-1408** [comment]
Hi, I am willing to work on this bug ! Can you assign this bug work to me
