### ISSUE TITLE
Use icons with color in priority key

### ISSUE THREAD

**Issue by digilou** [thedaviddias/Front-End-Checklist#335]
The priority color key works for me, but I'm not colorblind. It might be helpful for folks who experience red/green colorblindness to have an icon or number to help represent priority as well. The color idea can remain (red icon, yellow icon, green icon), but shouldn't be the only indicator of priority.

![image](https://user-images.githubusercontent.com/8865558/65801091-b7309f00-e124-11e9-9429-df348d84d8a2.png)

Thanks to everyone who has contributed to this. It's got a lot of helpful reminders!

**Comment by woutfeys** [comment]
Maybe by the thickness of the text?

**Comment by digilou** [comment]
Thinking about it more, a screen reader user would benefit from knowing each item is prioritized as. Oddly enough, the SVGs are marked as `aria-hidden="true"` which makes it invisible to screen readers, even when an `aria-label` is given. I think that's another issue to submit, though...
