### ISSUE TITLE
We can automatically test frontend checklist ?

### ISSUE THREAD

**Issue by khacthienonline** [thedaviddias/Front-End-Checklist#339]
We can automatically test frontend checklist use node js by input the link page ?
To avoid the repeat when checking website all page

**Comment by l1kw1d** [comment]
maybe looking at Google puppeteer https://pptr.dev/ or easier using lighthouse https://github.com/GoogleChrome/lighthouse

**Comment by l1kw1d** [comment]
Actually i can cover nearly 85% of the checklist just with selenium and webdriver.io , we could try to introduce the checklist in a small git app that will auto add the checklist to projects supported with auto-task to launch the checklist verification at time define by users

**Comment by patrickhulce** [comment]
[lighthouse](https://github.com/GoogleChrome/lighthouse) out of the box checks for about 50% of the checklist already and can be extended with plugins to cover the other items in the checklist that make sense for your site.

If anyone here would like to make a lighthouse plugin for the other items or suggest they be included in core, don't hesitate to reach out. We share the same goals :)

**Comment by thedaviddias** [comment]
Hey @patrickhulce! That was on my long list of things to do! I will let you know if I'm able to have something for lighthouse 😉
