### ISSUE TITLE
Add API section?

### ISSUE THREAD

**Issue by brillout** [thedaviddias/Front-End-Checklist#381]
Hi @thedaviddias !

Would you be interested in adding an API section? Talking about REST, GraphQL and RPC.

I'd gladly contribute :)

I'm the author of an RPC implementation ([Wildcard API](https://github.com/reframejs/wildcard-api#readme)).

**Comment by thedaviddias** [comment]
Hi @brillout! I'm actually working on the V2 of the Front-End Checklist, I believe it would be more interested if you add elements on the new version. What do you think?

**Comment by brillout** [comment]
Where can I see the V2? I've looked at the branches and your repository list but couldn't find any mentions of V2.

I really like your checklists because you seem to value "the search of the truth" above anything else.

There is a lot of confusion in the realm of APIs; it would be exciting to bring clarity on this topic.

I think we could do a beautiful section on APIs!

I'd love to check out the V2 and then suggest a list of API subjects we could write about. What do you think?

**Comment by lgmorand** [comment]
IMHO, it would not be "frontend" anymore and if you start with API, then you need to cover cookies, authentication and then the database, it's never ending.
