### ISSUE TITLE
Printing broken under firefox

### ISSUE THREAD

**Issue by lgmorand** [thedaviddias/Front-End-Checklist#393]
I don't know if it's me only, but only underfirefox printing is broken. I have a blank page, then a cropped page (with a part of the list) and then another blank page. I get the same behavior with two computers

Any idea what could cause that ?

![the frontend ckl bug](https://user-images.githubusercontent.com/6757079/77253185-03cee000-6c59-11ea-9384-5cf652023b84.png)

**Comment by thedaviddias** [comment]
Hi @lgmorand, not sure why, I can take a look.

**Comment by lgmorand** [comment]
activity :)

**Comment by Klemart3D** [comment]
Same problem as @lgmorand and when I checked all "HTML" items, they are not checked on printed page (see "100 % HTML items are ✓" but they are not).
Same with Firefox or Chrome (on Mac), see attached pdf files:
[Firefox-checklist.pdf](https://github.com/thedaviddias/Front-End-Checklist/files/5244267/Firefox-checklist.pdf)
[Chrome-checklist.pdf](https://github.com/thedaviddias/Front-End-Checklist/files/5244268/Chrome-checklist.pdf)

**Comment by Klemart3D** [comment]
Please be patient @stale
