### ISSUE TITLE
Generate PDF Report

### ISSUE THREAD

**Issue by atoaugustyn** [thedaviddias/Front-End-Checklist#407]
Hello @thedaviddias ,
Could PDF option be added to generate Generate report checklist.

**Comment by thedaviddias** [comment]
Hi @atoaugustyn, you can easily generate the report in PDF using the "print" on any browser. [Follow this link](https://www.digitaltrends.com/computing/how-to-save-a-webpage-as-a-pdf/) to see more details about how to do it.
