### ISSUE TITLE
No digests for javascript files names?

### ISSUE THREAD

**Issue by omenking** [thedaviddias/Front-End-Checklist#41]
After concat and mini/uglify you generate a digest in the javascript file name.

eg. `application-xxxx.js`

It ensures that when js files change the cached version doesn't persist because it has a different name.

**Comment by thedaviddias** [comment]
Yes @omenking, it's a good practice to have, do you want to make a PR and add some details about? But I wonder if it needs to be in the Front-End vs Back-End side? I know the digest can be generated by tools like gulp but it is something I'm not sure it's something that needs to be on the checklist... What do you think?

**Comment by omenking** [comment]
It depends if you consider tools such as gulp, webpack etc...  front-end tools.
I think they are and would put them into the scope of 'front-end'

In order to insert such a url it would need to work with a template engine or a gulp script that would modify and replace with the latest cached digest.

I don't think it hurts to mention it, it just might be not worth-wild or tricky for websites then vs web-apps.

**Comment by thedaviddias** [comment]
Don't hesitate to do a PR to add something about that to the checklist! Like you said, *it hurts not to mention it*. 😉
