### ISSUE TITLE
Missing README_APP

### ISSUE THREAD

**Issue by mbiesiad** [thedaviddias/Front-End-Checklist#411]
Missing 'README_APP' file. Line 69 of README.md.

Here:
"You can contribute to the Front-End Checklist App reading the **README_APP** file which explains everything about the project."
https://github.com/thedaviddias/Front-End-Checklist/blob/master/README_APP.md

Result:
```404 - Page not found```

Greetings,

**Comment by Upinder123** [comment]
i can help resolving this

**Comment by mbiesiad** [comment]
Good to know, thanks, but it's already fixed (see 413). Closed.
