### ISSUE TITLE
Namespacing JS and RAIL for Performance

### ISSUE THREAD

**Issue by jimimaher** [thedaviddias/Front-End-Checklist#42]
It might be worth mentioning namespacing with JavaScript to keep things out of the global scope. I have found it's always important to namespace JS to limit conflict possibilities with other code that you may not be aware of. https://www.safaribooksonline.com/library/view/learning-javascript-design/9781449334840/ch13s15.html

Also, the RAIL performance concepts from Google are must have for UI performance. https://developers.google.com/web/fundamentals/performance/rail

**Comment by thedaviddias** [comment]
Hi @jimimaher, yes indeed is a best practice, but also depends on how you are structuring your website. Namespacing JavaScript using a JS Framework or ES6 is not really relevant on my POV. I'm not sure if that needs to be on that checklist... What do you think?

**Comment by jimimaher** [comment]
@thedaviddias I'm thinking you're right. If anything, maybe a line about "any global variables are not generic..." would be helpful but still may not apply to all applications. Thanks!
