### ISSUE TITLE
For better accessibility, use different shade + color on priority pictograms

### ISSUE THREAD

**Issue by Klemart3D** [thedaviddias/Front-End-Checklist#423]
It would be great to use on [website](https://frontendchecklist.io/) same [priority images](https://github.com/thedaviddias/Front-End-Checklist/tree/master/data/images/priority) as github's readme.

Only color difference can be hard to read for people with visual difficulties.

**Comment by thedaviddias** [comment]
Yeah, I changed on the Github readme but didn't change on the website. Will do asap.

**Comment by Klemart3D** [comment]
Does website's sources can be added to GitHub to allow us to improve it?

**Comment by thedaviddias** [comment]
Of course, you can propose any PR if you want to.

**Comment by Klemart3D** [comment]
Where can I found website's sources to propose PR to improve it?
