### ISSUE TITLE
Different title between tools button and its SVG icon

### ISSUE THREAD

**Issue by Klemart3D** [thedaviddias/Front-End-Checklist#424]
On [website](https://frontendchecklist.io/), seems not very understandable to have different title between an html tool button and the SVG icon associated. Eg, on mouse hover for "uncheck all" button :

![titles](https://user-images.githubusercontent.com/7419525/94706369-66104800-0342-11eb-9f11-25afbd2e7c8a.jpg)

**Comment by Klemart3D** [comment]
:(

**Comment by gurnoor-garry** [comment]
Hey 
I wanna work on this issue. Could u please assign it to me?
