### ISSUE TITLE
HTML markup showing

### ISSUE THREAD

**Issue by mauriciabad** [thedaviddias/Front-End-Checklist#434]
The website displays "\<code>lang\</code>" instead of "`lang`"

![](https://user-images.githubusercontent.com/12821361/102088664-861cb700-3e1b-11eb-9094-684a4d42f154.png)

**Comment by onkar95** [comment]
I would like to contribute it
I had fixed it

**Comment by alishahzil** [comment]
the issue is still available

**Comment by naeempushia** [comment]
the issue is still available[,](https://weldingzilla.com/) or are you solved this?

**Comment by Sanyam17-beep** [comment]
im new to this can anyone help me

**Comment by thedaviddias** [comment]
Hey everyone, sorry for the silence. I will fix this in my next PR.
