### ISSUE TITLE
Title of videos in details are bigger than other docs/tools titles

### ISSUE THREAD

**Issue by Klemart3D** [thedaviddias/Front-End-Checklist#464]
Sometimes YouTube videos are "Documentation", sometimes they are "Videos". When it's Videos, the title displayed is bigger than other resources titles:

![video](https://user-images.githubusercontent.com/7419525/140722981-98dea438-12ca-4062-b39d-ff68b2caac2d.jpg)

**Comment by Aditya123987** [comment]
I have commited changes and fixed the font size of video titles . I am new to open source so now what should i do next?

**Comment by Aditya123987** [comment]
Sir, i have worked on it and submitted my pull request. I am new to open source . Can you guide me what to do next??

**Comment by DawnArchi01** [comment]
Hey @Klemart3D , I want to work on the issue
