### ISSUE TITLE
Add theme color meta tag (Feature request).

### ISSUE THREAD

**Issue by georgebawesome** [thedaviddias/Front-End-Checklist#465]
Not an issue, a feature request.
Please create a checkbox for adding theme color. Like,
```<meta name="theme-color" content="#fafafa">```

MDN Reference - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

**Comment by alamsameer** [comment]
hii @georgebawesome  can you assign to me so i can work on it

**Comment by alamsameer** [comment]
And i am new to open source and if we can discuss little bit about this ,that would be easy to work on this.

**Comment by georgebawesome** [comment]
Ofcourse, since the project is open source, you can fork it and create a pull request. There is no need of assigning.

**Comment by georgebawesome** [comment]
Now on PR #467
