### ISSUE TITLE
favicons can be SVG

### ISSUE THREAD

**Issue by Rudxain** [thedaviddias/Front-End-Checklist#486]
The `<link rel=icon>` element supports `image/svg+xml` value at the `type` attribute, why is this information not present in the `README.md`? Modern browsers already support SVG icons, although they're not recommended for legacy browsers

**Comment by trishit78** [comment]
Hello, is this project still open?? if yes ,I would love to work on this, and see if I can contribute to the project.
I am a first timer to contribute in open source...

**Comment by therushikale** [comment]
@thedaviddias hey , we would like to take up this issue and solve it.
Contributors: @KhanSumaiyaS@Komalkale25@Raghavvvv

**Comment by therushikale** [comment]
Hello sir,
Am i assigned for this issue? will you confirm it.

**Comment by Rudxain** [comment]
Since nobody has opened a PR for this, I guess I'll do it

**Comment by shubham369963** [comment]
sir i am the beginner frontend developer can you  sign something so that i can contribute in your repo

**Comment by Rudxain** [comment]
@thedaviddias Please reply

**Comment by Rudxain** [comment]
@shubham369963 Are you talking to me?

**Comment by Rudxain** [comment]
@stale why "completed" and not "not planned"? Is the bot not updated?
