### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by farhandotdev** [thedaviddias/Front-End-Checklist#488]
Adding the css grid checklist.

**Comment by kumarsanu2002** [comment]
Hii ,@farhandotdev .Let me know if i can do this. It would be my first contribution.
And let me know where to make changes and what changes.

**Comment by farhandotdev** [comment]
Go through the repo's url link and see what you want to changes @kumarsanu2002 , and then first you should clone the repo and then **make your own changes file**. And after that you make a pull requests.

**Comment by kumarsanu2002** [comment]
Ok @farhandotdev . I will do it by today.
And thanks.

**Comment by Jayteezany** [comment]
Hello Man, let me help fix the problem.

**Comment by OnonobiFavour** [comment]
Hello, I can help fix this

**Comment by farhandotdev** [comment]
sure do it!

**Comment by farhandotdev** [comment]
sure do it!

**Comment by therushikale** [comment]
@thedaviddias hey , we would like to take up this issue and solve it.
Contributors: @KhanSumaiyaS@Komalkale25@Raghavvvv

**Comment by therushikale** [comment]
@thedaviddias@farhandotdevhey , we would like to take up this issue and solve it.
Contributors: @KhanSumaiyaS@Komalkale25@Raghavvvv

**Comment by thedaviddias** [comment]
@therushikale Stop spamming!

**Comment by noamangg** [comment]
it is a great resource to learn from, thank you all

**Comment by Anju3750** [comment]
Hello can I fix this issue
