### ISSUE TITLE
Image elements do not have explicit width and height

### ISSUE THREAD

**Issue by Jayteezany** [thedaviddias/Front-End-Checklist#489]
I realized that image element does not have explicit width and height i would like to fix it.
![image](https://user-images.githubusercontent.com/101563959/185300516-20762390-d8a0-4e39-b3be-63c7bdfa6cb6.png)

**Comment by faha1999** [comment]
`<img width="100%" height="40" alt="" src="your_url">`
or
`<img width="40" height="40" alt="" src="your_url">`

define the width and height of the image using the **width** and **height** attributes.

**Comment by Zeinshirou04** [comment]
or sometimes for me, if i want to make all the img have the same width, i use css such
`img {
    width: 20%;
}`
so i dont have to define all the img width one by one

**Comment by kaushalyaghadge** [comment]
I would like to help to solve this issue

**Comment by trishit78** [comment]
Hello, is this project still open?? if yes ,I would love to work on this, and see if I can contribute to the project.
I am a first timer to contribute in open source...

**Comment by therushikale** [comment]
<img  src="img_url" width="100%" height="100%" alt="img_name"  >

So the <img> tag  holds the whole space for the referenced image.

**Comment by trishit78** [comment]
Am I assigned for the issue?
Thank you :)

**Comment by therushikale** [comment]
@thedaviddias hey , we would like to take up this issue and solve it.
Contributors: @KhanSumaiyaS@Komalkale25@Raghavvvv
