### ISSUE TITLE
Buttons 

### ISSUE THREAD

**Issue by Oluthefirst** [thedaviddias/Front-End-Checklist#492]
Buttons cursor should be set as pointer to show users it is clickable @JeffreyATW

**Comment by Oluthefirst** [comment]
I would love to add this fix

**Comment by mnosov622** [comment]
Hello @Oluthefirst !

Can I work on this issue, please ?

**Comment by jayakanthansubramani** [comment]
can i work on this issue?

**Comment by its-abhishek** [comment]
I want to work on this

**Comment by Akashzxr** [comment]
is anyone working on this issue?

**Comment by constneophyte** [comment]
Is anyone working on this yet?

**Comment by Anju3750** [comment]
Can I work on this

**Comment by Sagargupta16** [comment]
Can You assign this to me i can take care about this issue.

**Comment by sumit851** [comment]
plz assign me to this issue. I want to contribute

**Comment by bzaman** [comment]
@Oluthefirst could please describe where it is. It seem clickable element get pointer where needed.

**Comment by iamnishantgaharwar** [comment]
Hii I'm new to opensource community if anyone here knows any project that i can contribute on please let me know

**Comment by bzaman** [comment]
@iamnishantgaharwar Welcome to the world of open sources. Do some google/youtube search on how to contribute to any open source project you like based on your interest and knowledge. https://github.com/explore would be a good place to go through projects if you like. Thank you.

**Comment by iamnishantgaharwar** [comment]
@bzaman Okay thanks for the suggestion
