### ISSUE TITLE
5xx errors and external resources

### ISSUE THREAD

**Issue by joriszwart** [thedaviddias/Front-End-Checklist#50]
> Remember that the 5xx error page needs to have his CSS integrated (no external call on the current server).

I cannot not find any source for this. Does [RFC 2616](https://tools.ietf.org/html/rfc2616#page-70) mention this in some way?

**Comment by thedaviddias** [comment]
Hi @joriszwart, I put that for a simple reason, when you have an issue on a server, it happens that some resources can be inaccessible too. It's in general better to integrate the CSS and eventually the JS into the page.

I see that as a personal recommendation, so I'm not sure if that is written somewhere.

**Comment by joriszwart** [comment]
Plausible!

**Comment by famer** [comment]
That's questionable, because 5xx could be result not of the server's down state, but server failure with particular request, "not implemented", data errors, etc...
