### ISSUE TITLE
Suggestion: Add a table of contents for easy navigation.

### ISSUE THREAD

**Issue by FrozenHearth** [thedaviddias/Front-End-Checklist#502]
Similar to this: https://github.com/sudheerj/javascript-interview-questions#table-of-contents

Right now, it's difficult to navigate. Adding a table of contents would make the navigation simpler.

**Comment by ashutoshofficial25** [comment]
hello! @FrozenHearth  how can I contribute in this issue..? I'm new at open source contribution. please help me out.!

**Comment by FrozenHearth** [comment]
@ashutoshofficial25 Please go to the link in my original comment and look for the source code. That will give you an idea.

**Comment by eli-ott** [comment]
Hello @FrozenHearth! I would love to contribute. I'm new to open source contribution, but I'd do my best to help you with this suggestion.
