### ISSUE TITLE
Paragraph repeats in README.md

### ISSUE THREAD

**Issue by aras72h** [thedaviddias/Front-End-Checklist#522]
There is two paragraphs almost exactly the same.

![image](https://github.com/thedaviddias/Front-End-Checklist/assets/43763536/4332035b-5962-4c69-a4ff-1d97765987e0)

**Comment by ShyamPraveenSingh** [comment]
Hi @thedaviddias I would like to work on this issue, you can assign it to me

**Comment by T1rth1** [comment]
Heyy @thedaviddias there is two paragraph exactly the same in How to use? section..then if you assign this task to me then i would like to work on this issue
