### ISSUE TITLE
Virus?!?

### ISSUE THREAD

**Issue by fadsasd** [thedaviddias/Front-End-Checklist#549]
When i visit the website, it says is a virus. Can someone comfirm?!

**Comment by carstenjaksch** [comment]
Uninstall your anti-virus software. Only slows down your PC.

**Comment by rngala** [comment]
Probably the warning could be created by your browser or Anti-virus settings. It's your browser telling you "this site is on the Google Safe Browsing list of phishing sites". Happens mostly with Chrome, sometimes reading from scripts. Most browsers will do that for precaution.
