### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by miya0001** [thedaviddias/Front-End-Checklist#58]
Hi,

It is just a ping. 😊 

I translated it to Japanese.
https://github.com/miya0001/Front-End-Checklist

It is really nice work and helps us very much, Thanks.

Feel free to close this issue.  😊

**Comment by thedaviddias** [comment]
Whoo! That's really nice @miya0001! Thanks a lot for that. I just add a section with your link on the Front-End Checklist! I will send you a ping when my Checklist Web app will be ready. I wish you will be able to help me for the translation!

**Comment by miya0001** [comment]
Oh thanks!

> I will send you a ping when my Checklist Web app will be ready.

Nice 👍  I am looking forward to seeing your app. 😃

**Comment by Dreamersoul** [comment]
Clicking on the Japanese flag on the website bugs out, should I open an issue for that?
