### ISSUE TITLE
Labels, Search or Sorting

### ISSUE THREAD

**Issue by rubenvarela** [thedaviddias/Front-End-Checklist#59]
Since the list itself is not sorted, I was trying to find the items marked `HIGH`. 

The way it's constructed right now, it doesn't allow the search to work. 

As a Enhancement to the list, I was thinking maybe they could be split into sections or possibly split into sections - High, Medium, Low - which would allow to easier go through the list. 

If not, another option might be to add something besides the image that we could use that works with the built in browser search.

**Comment by thedaviddias** [comment]
Hi @rubenvarela, indeed, someone already shared his difficulties to to have the list sorted.

Do you think, putting "High" first and "Medium" and "Low" after can facilitate?

**Comment by rubenvarela** [comment]
I was looking at the list. Maybe an icon could be used to show High, Medium, Low. For example, a red exclamation mark, yellow triangle, green... (not sure which icon). After that icon, add the word High, Medium, Low. 

> **Doctype:** <!> High – The Doctype is HTML5 and is at the top of all your HTML pages

That would allow for some color which helps draw attention to the level and also allows searching using "High", "Medium", "Low"

**Comment by thedaviddias** [comment]
Hi @rubenvarela, I prefer to review any big change after launching the Front-End Checklist Web App. You'll be able to filter and sort easily 😀.

I will maintain the issue open until I finish it in the next days.

**Comment by thedaviddias** [comment]
Hey @rubenvarela! Check the new online app! (http://frontendchecklist.com)

**Comment by chinesexiaozhu** [comment]
this is a good adivce

**Comment by thedaviddias** [comment]
Ping @rubenvarela
