### ISSUE TITLE
Meta tags to indicate paginated content

### ISSUE THREAD

**Issue by ferdiemmen** [thedaviddias/Front-End-Checklist#61]
Hi @thedaviddias,

I saw the checklist is missing link tags for paginated lists. The following `<link>` tags would be added in the `<head>` on page 2 of a paginated list. 

```
<link rel="prev" href="https://example.com/?page=1">
<link rel="next" href="https://example.com/?page=3">
```

See: https://support.google.com/webmasters/answer/1663744?hl=en

**Comment by thedaviddias** [comment]
Hi @ferdiemmen, yes indeed, I removed that from my original list. I need to find some articles I read about that recently which put me in doubt if it's really needed.

Let me find that and I'll let you know about in max 2 days! 😉

**Comment by thedaviddias** [comment]
Hey @ferdiemmen! I didn't find what I had in mind. I think we can add that point, do you want to do a PR or I can do?

**Comment by ferdiemmen** [comment]
Hi @thedaviddias!
I'm gonna make a PR. I think we should add it to the SEO section? Do you agree?

**Comment by thedaviddias** [comment]
Yes absolutely! You can eventually that tool I found (https://technicalseo.com/seo-tools/rel-prev-next/) or another if you have one.

**Comment by ferdiemmen** [comment]
@thedaviddias Dunno if you got a mail from git. But here is the PR: https://github.com/thedaviddias/Front-End-Checklist/pull/155

**Comment by thedaviddias** [comment]
Thanks for the PR!
