### ISSUE TITLE
Addition in Performance: Chrome Audit Report

### ISSUE THREAD

**Issue by kailashvele** [thedaviddias/Front-End-Checklist#63]
Chrome's Audit provides more insights to the performance, accessibility, pwa and best practices. Those can help to build a better performant site. Let me know if you want me to add that to the repo. Cheers!

**Comment by thedaviddias** [comment]
Hey @kailashvele! Yes sure, don't hesitate to propose a PR! Thanks!

**Comment by webdevan** [comment]
Perhaps a whole section at the end linking to automated testing tools for final checks? Lighthouse, Pagespeed insights, Passmarked, SEO crawlers, etc.

**Comment by thedaviddias** [comment]
@webdevan, yes, absolutely, it's something I want to add in the next days, but fill free to put a list here if you want.

**Comment by kailashvele** [comment]
I always have the dilemma whether there should be checklist for three phases 1) Before development 2) While development and 3) After development. 

But then if the objective is to make sure that things are correct before going to Production then the 3rd one is fine. 

But performance and all those factors are pretty tedious to tackle if checked at the end and developers most of time opt out of it due to the time that needs to be invested. So should there be 2 phases of checklist?

**Comment by thedaviddias** [comment]
Interesting point indeed @kailashvele. Elements in the checklist are to be taken into consideration during the development. I don't think people need to "check" that list only before going to production.

It's not easy to separate these elements into different phases, performance is related to what the developer do during the development but also at the end. Don't hesitate to go on [Gitter](https://gitter.im/Front-End-Checklist/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) if you want to exchange more about.

**Comment by praveeno** [comment]
https://developers.google.com/web/tools/lighthouse/ this is another tool from chrome

**Comment by thedaviddias** [comment]
@kailashvele, I'm looking to add maybe a tag on the Front-End Checklist app with "at the beginning", "During development", "End of development", what do you think?

**Comment by kailashvele** [comment]
@thedaviddias Yes I would like to see this, Will help lot of developers to ensure nothing is missed out and is taken care of from the beginning. DM me twitter to talk more on this. :)
