### ISSUE TITLE
Spanish translation *work-in-progress*

### ISSUE THREAD

**Issue by eoasakura** [thedaviddias/Front-End-Checklist#67]
Hi, i forked this repo and started a Spanish translation. You can find it here: [Front-End Checklist-ES](https://github.com/eoasakura/Front-End-Checklist-ES)

The `README.md` is almost done. If someone can help with fixes or examples on Spanish that would be cool. `CODE_OD_CONDUCT.md` file pending.

Any help with translation would be great.

Thanks to everyone making this project.

**Comment by thedaviddias** [comment]
Hi @eoasakura, thank you so much for that work! I just pushed a reference to your translation. I hope it will help you to find some people!

I will keep that issue open for few days 😉

**Comment by FreakDroid** [comment]
@eoasakura  I was checking the translation (only I scanned but when I have time go on details) and I think was awesome but the only thing that I can suggest and help is, putting the link's label in spanish and in the end (English) for instance:

Original link:

> 📖 [Mobile Input Types](http://mobileinputtypes.com/)

Translated link:

> 📖 [Tipos de entradas en móvil](http://mobileinputtypes.com/) (Fuente en Íngles)


What do you think? I think when the reader is reading the doc, won't feel that the document is not full translated.

Thanks guys.

**Comment by eoasakura** [comment]
Seems like a good idea and make more sense, I'm going to try and make changes but if you have time, feel free to make a pull request for it.

Thanks for the suggestion

**Comment by FreakDroid** [comment]
@eoasakura Ok, I forked your repo and today at evening I should start. Thank you guys :smile:
