### ISSUE TITLE
Korean Translation is work in progress

### ISSUE THREAD

**Issue by kesuskim** [thedaviddias/Front-End-Checklist#69]
Hello! I forked this repository and started to work to translate into Korean. Here is repo; [here](/kesuskim/Front-End-Checklist)

I just forked it, so have some things to do bit, but will do within 2 days. :)

Thank you for making this project.

**Comment by thedaviddias** [comment]
Hi @kesuskim and thanks for starting that work! I'll leave the issue open for few days to help you to find some people to help you.

I just added your repo in the "Translation" section. Good luck and thanks for your work and support!
