### ISSUE TITLE
Integrate with Lighthouse

### ISSUE THREAD

**Issue by alizain** [thedaviddias/Front-End-Checklist#7]
While the checklist is awesome, it would be more usable if it were integrated into an automated testing tool. Perhaps it would be worth adding them to [Lighthouse](https://github.com/GoogleChrome/lighthouse)

**Comment by thedaviddias** [comment]
I was planning to build a simple but useful web app. I didn't think about adding some elements on Lighthouse...

**Comment by alizain** [comment]
I was thinking the same (automating the checklist), but then I realized that Lighthouse exists, and it doesn't include any of these checks. The API is well designed, tests are organized by section, and it's really flexible, so you'd actually be able to test all these things fairly easily. And it runs on Chrome and Firefox (I think), so it would be a great all-in-one tool, without having to run/maintain/download something else.

I'd be happy to help you with it, if you'd like.

**Comment by alizain** [comment]
Relevant [architecture document](https://github.com/GoogleChrome/lighthouse/blob/master/docs/architecture.md) and [recipe for custom audit](https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit) - fairly straightforward...

**Comment by thedaviddias** [comment]
If you want to try adding some elements on Lighthouse, don't hesitate! The checklist is in public domain so you can use it as much and how you want 😊

I'll not be able to work on that at that time but probably soon.

**Comment by alizain** [comment]
Understandable. Unfortunately I won’t have much time either. Just wanted to share an idea, and perhaps supplement your effort.

**Comment by thedaviddias** [comment]
Thanks @alizain! Let's exchange about that soon and try to see what we can do on Lighthouse, maybe together 😉

**Comment by Jesuuelx** [comment]
hjbhj
