### ISSUE TITLE
Making this part of a build process

### ISSUE THREAD

**Issue by karllhughes** [thedaviddias/Front-End-Checklist#74]
I'm a big checklist fan, so thanks for making this. Have you heard of any effort to make the checklist part of an automated build/test process? For example, having a step in a travis build process that will fail if the home page of your site (or other URLs) don't adhere to the checklist?

Just a thought. I don't think I have the technical chops to implement this, but would love to see it.

**Comment by thedaviddias** [comment]
@karllhughes, yes it's something that few people seems to be asking. For now, I'm working on a new page for frontendchecklist.com. Just after, I have few options:
- doing from scratch a tool to give the possibility to test single HTML pages
- find a way to integrate some tests on [LightHouse](https://developers.google.com/web/tools/lighthouse/)
- I need to see if I can implement something on travis, codecoverage or other tools like that.
- Maybe a third option I didn't find yet 😀

I'll keep everyone posted. Don't hesitate if you have any idea or if you want to participate!

**Comment by MikeParkin** [comment]
How about building a command line application that you could pass either a local static HTML file or a URL to and have it scan and produce output for each rule.

It is possible to build apps like this quite quickly using PHP (which I imagine is used a lot for people building websites and looking at these links). It's possible to build them using a very lightweight symfony console application ( https://symfony.com/doc/current/components/console/single_command_tool.html ) and then package it into a single file via a PHAR using Box (https://box-project.github.io/box2/) this would make it possible to add all of the tests and compile it into a simple to download (and update) tool.

This would give you a lot of the scope for the future, things like an easy way to update the application when new features are added, forking ability for other users to build their own tests and have them merged into the project with pull requests, help, nicely formatted output etc.

Let me know if you think this is something you would be interested in as we really like the project and might be able to spare some resource to make it a reality.

**Comment by MikeParkin** [comment]
ping @thedaviddias :)

**Comment by thedaviddias** [comment]
Hey @MikeParkin, sorry for the delay: I was trying to finish the first beta of the Front-End Checklist. A command line tool is in the pipe :) I have few other projects to launch before but it's something that can definitely be interesting (especially if it's open-source).
