### ISSUE TITLE
Brazillian Portuguese translation - Work in Progress

### ISSUE THREAD

**Issue by jcezarms** [thedaviddias/Front-End-Checklist#75]
I am vastly grateful for this checklist, so I think this is the smallest thing I could do for it.

[This](https://github.com/jcezarms/Front-End-Checklist) is the fork, some remarks:
- Just finished the README translation;
- I translated most of the documentation articles' titles for readability, do ping me back if you think it's better to revert them;
- Should have the Code of Conduct done by two days from now - or at the very most, end of the week.

Hope we'll make this an i18n checklist :flags:

**Comment by jcezarms** [comment]
Actually just finished the Code of Conduct translation. \o

**Comment by thedaviddias** [comment]
Oi @jcezarms, até podia ter feito também a traduçao mas o tempo me faltou! Muito obrigado pela contribiuçao e ajuda! 

Vendo o impacto desse projeto, sim tudo vai ser feito para facilitar a internacionalização da lista.

Estou agora mesmo trabalhando numa amelioraçao da pagina que se vê no endereço frontendchecklist.com.

**Comment by jcezarms** [comment]
Opa! Isso é extremamente animador! Pode me acionar se for interessante a ajuda em qualquer ponto, estou à disposição. :blush:

**Comment by thedaviddias** [comment]
@jcezarms ah sim, esqueci de falar que addicionei seu repo na parte "[Translation](https://github.com/thedaviddias/Front-End-Checklist#translation)". Até! 😉

**Comment by atempel** [comment]
There are still the need for the app translation? I'm up to it
If so, what code do I use for the name of the folder? "pt-br"?

**Comment by thedaviddias** [comment]
Yes it's a need to translate the JSON files if you have some time. "pt-br" should be working but if you find any issue, don't hesitate to tell me.

**Comment by atempel** [comment]
Will do!
