### ISSUE TITLE
Convert `[ ]` to checkboxes on http://frontendchecklist.com/

### ISSUE THREAD

**Issue by edbrannin** [thedaviddias/Front-End-Checklist#76]
The homepage isn't showing GitHub-style checkboxes at the start of each item.

Perhaps this can be fixed in the build process?

On GitHub:

![image](https://user-images.githubusercontent.com/121909/31963823-059dd43e-b8d0-11e7-87f5-1fecbf10386a.png)

Homepage:

![image](https://user-images.githubusercontent.com/121909/31963845-150aec72-b8d0-11e7-8ef8-1ccd69550e33.png)

**Comment by thedaviddias** [comment]
Same response [#77](https://github.com/thedaviddias/Front-End-Checklist/issues/77), can't be fixed for now.

**Comment by thedaviddias** [comment]
@edbrannin Now you can check the 🔥 NEW Front-End Checklist Application 🔥, it's dynamic and can manually generate reports! Enjoy 🎉! ➜ http://bit.ly/frontendchecklist

**Comment by edbrannin** [comment]
Wow, great work!
