### ISSUE TITLE
High/Medium/Low buttons have excessive margin/padding on Chrome (Win7)

### ISSUE THREAD

**Issue by edbrannin** [thedaviddias/Front-End-Checklist#77]
High/Medium/Low buttons have excessive margin/padding on Chrome (Win7)

On GitHub:

![image](https://user-images.githubusercontent.com/121909/31963823-059dd43e-b8d0-11e7-87f5-1fecbf10386a.png)

Homepage:

![image](https://user-images.githubusercontent.com/121909/31963845-150aec72-b8d0-11e7-8ef8-1ccd69550e33.png)

CSS rules:

![image](https://user-images.githubusercontent.com/121909/31963957-73479aec-b8d0-11e7-8cf7-23b3c90d961b.png)

Box-model view:

![image](https://user-images.githubusercontent.com/121909/31963913-58e954c4-b8d0-11e7-9f68-6c26bf006985.png)

**Comment by thedaviddias** [comment]
Hi @edbrannin, indeed, I saw that. Because I'm using a template generated by Github Pages, I can do modifications on the CSS.

But I'm working on a replacement for that page, please wait only few days, and the page will be visually better 😉

**Comment by tomekmy** [comment]
Hi. While working on a new version of the site you can add a selectable checkboxes feature with progress bar.

Something like this: https://jonyablonski.com/designers-wpo-checklist/#top

**Comment by thedaviddias** [comment]
Thanks @tomekmy, it's already implemented :)

Users will be able to see the progress of each section (head, images, html...).

But that could be a good idea to have a general bar too. Thanks for the link!

**Comment by thedaviddias** [comment]
Hey @tomekmy, have you tested the new Front-End Checklist App?

**Comment by tomekmy** [comment]
Wow. @thedaviddias amazing job!
That looks and works better then I imagined :)

One little suggestion. Maybe add border to checkboxes or change checkboxes appearance to be similar like a favicon.

**Comment by thedaviddias** [comment]
Thanks @tomekmy, really happy you liked it!

Good suggestion! Let me do some tests and see if it's better.

You mean the checked state or not checked?

**Comment by tomekmy** [comment]
Especially the unchecked state because at the first sight it looks like something you can't check and rather it is similar to 'list-style-type: square;'.
But it is only my UX feelings :)

**Comment by thedaviddias** [comment]
Can you take a look now? I just make the changes.

**Comment by tomekmy** [comment]
That's what I meant :+1: 
Great job!

**Comment by thedaviddias** [comment]
Thanks for the suggestion @tomekmy! 😅
