### ISSUE TITLE
Typo in first line of README

### ISSUE THREAD

**Issue by jakecarr** [thedaviddias/Front-End-Checklist#78]
### I think the README file should say:

The Front-End Checklist is an exhaustive list of all elements you need to have / to test before launching your site / **HTML page** to production.

### And not:

> The Front-End Checklist is an exhaustive list of all elements you need to have / to test before launching your site / page HTML to production.

**Comment by thedaviddias** [comment]
Thanks @jakecarr for that correction!

**Comment by thedaviddias** [comment]
Hi @jakecarr, I just pushed [your point](https://github.com/thedaviddias/Front-End-Checklist/commit/e2dc423fc1211fb30a694cb6ea4f1118481732de).

Thanks and don't hesitate to do a PR if you find something else ;)

**Comment by jakecarr** [comment]
No problem @thedaviddias 😄  I shall have a look
