### ISSUE TITLE
Minor typo 

### ISSUE THREAD

**Issue by SVGE** [thedaviddias/Front-End-Checklist#83]
Hi there! This checklist is super awesome and helpful, thanks! There’s a very minor typo/error that I caught: “Cross Site Request Forgery (CSRF): You are ensure that requests made to your server-side are...” 
Instead of “you are ensure”, I suggest just “you ensure (remove “are”). 

Nitpicking for sure! Thanks again for this. Cheers!

**Comment by thedaviddias** [comment]
Hi @SVGE! Thanks for the flag! All errors are important to be corrected so it's not nitpicking 😀

I [corrected it](https://github.com/thedaviddias/Front-End-Checklist/commit/a533379072575d7ddff443764fb85e39719f3266)!
