### ISSUE TITLE
Page size limited to 500KB?

### ISSUE THREAD

**Issue by antarestupin** [thedaviddias/Front-End-Checklist#95]
I don't see the arguments of limiting the page size to 500KB in the links under the recommandation in [the performance section](https://github.com/thedaviddias/Front-End-Checklist#best-practices-4). I agree that pages should be light, but 500KB seems arbitrary.

As the ideal size of a page depends on too many things, I would recommend to replace this limit by the use of a performance budget, which is more flexible than a fixed limit and a good way to make the team responsible about the pages size. Tools like [the performance budget calculator](http://www.performancebudget.io/) are very helpful to compute the budget.

Alternatively, if you want an interesting fixed limit, you can recommend to limit the size of the critical content to 14KB, so that the browser will be able to start rendering it during first TCP roundtrip. But that's an advanced practice, I'm not sure it would fit in this list.

**Comment by thedaviddias** [comment]
@antarestupin Instead of page weight, maybe response-time is more relevant. We can for example, say "Your response-time need to be inferior to 10 seconds? What do you think? https://www.nngroup.com/articles/website-response-times/

**Comment by antarestupin** [comment]
I agree, the initial goal should be expressed in term of seconds/ms as it's the actual user experience that you want to specify. But I don't think a strict value should be set in this checklist, because what's really important for the team is to define a goal, achieve it and keep it in consideration when changing things in the app. Then from this goal they can define an ideal page weight using tools like the one I mentioned above.

If you need inspiration for setting such a goal I recommend [the RAIL model](https://developers.google.com/web/fundamentals/performance/rail) which defines ideal performance goals (for page load it's 1 second).

**Comment by antarestupin** [comment]
@thedaviddias I'm reading the latest version of Smashing Magazine's [performance checklist](https://www.smashingmagazine.com/2018/01/front-end-performance-checklist-2018-pdf-pages/) and I see in the 7th section that they advise precise numbers concerning performance, to be exact:

- a First Meaningful Paint under 1 second
- a Time To Interactive under 5 seconds for the "minimum" configuration (a $200 Android on a slow 3G network with 400ms RTT and 400kbps transfer speed) and under 2 seconds for repeat visits
- a critical file size under 170Kb gzipped

What do you think of using these numbers as a recommendation, or at least using the same kind of template?

**Comment by thedaviddias** [comment]
Absolutely @antarestupin, I thought about the same thing when I read the performance checklist. Feel free to push some modifications into the README :)

**Comment by antarestupin** [comment]
Oops sorry I forgot to close this issue.
